import Head from 'next/head'
import Header from "@/components/layout/Header";
import Candy from "@/components/Candy";
import {useEffect, useState} from "react";
import Player from "@/models/Player";
import {CandyType} from "@/models/Candy";
import CandyList from "@/components/CandyList";
import PlayerStatus from "@/components/PlayerStatus";

export default function Home() {
  const candyTypes =
      [CandyType.MMS,
        CandyType.REESES,
        CandyType.KIT_KAT,
        CandyType.PEANUT_MMS,
        CandyType.BUTTERFINGER,
        CandyType.SNICKERS,
        CandyType.TWIX,
        CandyType.MILKY_WAY,
        CandyType.HERSHEYS,
        CandyType.MARS];
  const [player, setPlayer] = useState<Player | null>(null);

  useEffect(() => {
    setPlayer(new Player());
  }, []);

  return (
      <>
        <Head>
          <title>Candy Lord</title>
          <meta name="description" content="Generated by create next app"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Header name={"Candy Lord"}/>
        <main>
          <div className={"container"}>
            <div className={"row"}>
              {player &&
                  <>
                    <div
                        className={"col-12 col-sm-6 col-md-4 col-lg-4 p-0 border border-end-0 border-5"}>
                      <div className={"border-bottom text-center fw-bold"}>Drugs
                        on
                        Hand
                      </div>
                      <CandyList candyTypes={candyTypes} player={player}
                                 price={false}/>
                    </div>


                    <div
                        className={"col-12 col-sm-6 col-md-4 col-lg-4 p-0 border border-5"}>
                      <div
                          className={"border-bottom text-center fw-bold"}>Street
                        Prices
                      </div>
                      <CandyList candyTypes={candyTypes} player={player}
                                 price={true}/>
                    </div>


                    <div
                        className={"col-12 col-sm-12 col-md-4 col-lg-4 border border-5"}>
                      <div className={"row"}>
                        <div className={"col-12 border-bottom"}>
                          <div
                              className={"border-bottom text-center fw-bold"}>Stash
                          </div>
                          <ul className={"list-group"}>
                            {player.stash.candies.length > 0 ?
                                player.stash.candies.map((candy, index) => (
                                    <li key={index}
                                        className={"list-group-item d-flex flex-row justify-content-between border-0"}>
                                      <Candy name={candy.name}
                                             quantity={candy.quantity}/>
                                    </li>
                                )) :
                                <li className={"list-group-item d-flex justify-content-center align-items-center p-0 border-0 fw-semibold"}>Empty</li>}
                          </ul>
                        </div>


                        <div className={"col-12"}>
                          <div className={"row"}>
                            <PlayerStatus player={player} />
                          </div>
                        </div>
                      </div>
                    </div>
                  </>}
            </div>
          </div>
        </main>
      </>
  );
}
